basket/urls.py
from django.urls import path, include
from basket import views

app_name = 'basket'

urlpatterns = [
    path('players/list', views.players_list, name="players_list"),   
    path('players/create', views.player_create, name="players_create"),
    path('players/update/<int:pk>', views.player_update, name="players_update"),
    path('players/delete/<int:pk>', views.player_delete, name="players_delete"),
    path('teams/list', views.teams_list, name="teams_list"),
    path('teams/create', views.team_create, name="teams_create"),
    path('teams/update/<int:pk>', views.team_update, name="teams_update"),
    path('teams/delete/<int:pk>', views.team_delete, name="teams_delete"),
    path('coachs/list', views.coachs_list, name="coachs_list"),
    path('coachs/create', views.coach_create, name="coachs_create"),
    path('coachs/update/<int:pk>', views.coach_update, name="coachs_update"),
    path('coachs/delete/<int:pk>', views.coach_delete, name="coachs_delete"),
    path('matchs/list', views.matchs_list, name="matchs_list"),
    path('', views.home, name="home"),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basket/', include('basket.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

basket/models.py
from django.db import models



"""
Nombre entrenador
Edad
Email
Rut
Apodo
"""
class Coach(models.Model):
    name = models.CharField(max_length=150)
    age = models.PositiveIntegerField()
    email = models.EmailField()
    rut = models.CharField(max_length=12)
    nickname = models.CharField(max_length=80)

    def __str__(self):
        return self.name

"""
Nombre del team
Descripción del team
Logo del team
Código de equipo
"""
class Team(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField()
    code = models.CharField(max_length=20, unique=True)
    logo = models.ImageField(upload_to='teams/')
    coach = models.OneToOneField(Coach, on_delete=models.CASCADE)

    def count_player(self):
        return Player.objects.filter(team=self.pk).count()

    def __str__(self):
        return self.name

"""
Nombre jugador
Apodo
Fecha de nacimiento
Edad
Rut
Email
Estatura
Peso
Fotografía
Posición de juego (opciones: Base, Escolta, Alero, Ala-pivot, Pivot)
"""

POSITION_PLAYER = (
    ('BA', 'Base'),
    ('ES', 'Escolta'),
    ('AL', 'Alero'),
    ('AP', 'Ala-pivot'),
    ('PI', 'Pivot'),
)

class Player(models.Model):
    name = models.CharField(max_length=150)
    nickname = models.CharField(max_length=80)
    birthday = models.DateField()
    age = models.PositiveIntegerField()
    rut = models.CharField(max_length=12)
    email = models.EmailField()
    height = models.PositiveIntegerField(help_text='in centimeters')
    weight = models.PositiveIntegerField(help_text='in grams')
    photo = models.ImageField(upload_to='players/')
    position = models.CharField(choices=POSITION_PLAYER, max_length=2)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return '{name} ({team})' . format(name=self.name, team=self.team)



class Roster(models.Model):
    name = models.CharField(max_length=150)
    player = models.ManyToManyField(Player)

    def __str__(self):
        return self.name


class Match(models.Model):
    name = models.CharField(max_length=150)
    team1 = models.ForeignKey(Roster, related_name='team1', on_delete=models.CASCADE)
    team2 = models.ForeignKey(Roster, related_name='team2', on_delete=models.CASCADE)
    date = models.DateTimeField()

    def __str__(self):
        return '{name} ({team1} vs {team2})'.format(
            name=self.name,
            team1=self.team1,
            team2=self.team2
        ) 

basket/forms.py
from django import forms
from basket.models import Player, Team, Coach


class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = "__all__"


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = '__all__'


class CoachForm(forms.ModelForm):
    class Meta:
        model = Coach
        fields = '__all__'

basket/views.py
from django.shortcuts import render, redirect
from basket.models import (
    Team,
    Player,
    Coach,
    Match
)
from basket.forms import PlayerForm, TeamForm, CoachForm


def players_list(request):
    template_name = 'players_list.html'
    data = {}

    teams = Team.objects.all()

    for team in teams:
        team.players = Player.objects.filter(team=team)

    data['teams'] = teams

    return render(request, template_name, data)


def teams_list(request):
    template_name = 'teams_list.html'
    data = {}

    data['teams'] = Team.objects.all()
    return render(request, template_name, data)


def coachs_list(request):
    template_name = 'coach_list.html'
    data = {}
    data['coachs'] = Coach.objects.all()

    return render(request, template_name, data)


def matchs_list(request):
    template_name = 'matchs_list.html'
    data = {}

    data['matchs'] = Match.objects.all()

    return render(request, template_name, data)


def home(request):
    template_name = 'home.html'
    data = {}

    data['last_5_matchs'] = Match.objects.all().order_by('-pk')[:5]
    data['last_5_players'] = Player.objects.all().order_by('-pk')[:5]
    data['teams'] = Team.objects.all()

    return render(request, template_name, data)


def player_create(request):
    template_name = 'players_create.html'
    data = {}
    data['form'] = PlayerForm(request.POST or None)

    if data['form'].is_valid():
        data['form'].save()
        return redirect('basket:players_list')

    return render(request, template_name, data)


def team_create(request):
    template_name = 'team_create.html'
    data = {}
    data['form'] = TeamForm(request.POST or None)

    if data['form'].is_valid():
        data['form'].save()
        return redirect('basket:teams_list')

    return render(request, template_name, data)


def coach_create(request):
    print("aaaaaaaaaaaaaa")
    template_name = 'coach_create.html'
    data = {}
    data['form'] = CoachForm(request.POST or None)

    if data['form'].is_valid():
        print("coach saved")
        data['form'].save()
        return redirect('basket:coachs_list')

    else:
        print("not saved")

    return render(request, template_name, data)


def player_update(request, pk):
    template_name = 'players_update.html'
    data = {}

    player = Player.objects.get(pk=pk)
    data['form'] = PlayerForm(request.POST or None, instance=player)

    if data['form'].is_valid():
        data['form'].save()
        return redirect('basket:players_list')

    else:
        print("not saved")

    return render(request, template_name, data)


def coach_update(request, pk):
    template_name = 'coach_update.html'
    data = {}

    coach = Coach.objects.get(pk=pk)
    data['form'] = CoachForm(request.POST or None, instance=coach)

    if data['form'].is_valid():
        data['form'].save()
        return redirect('basket:coachs_list')

    else:
        print("not saved")

    return render(request, template_name, data)


def team_update(request, pk):
    template_name = 'team_update.html'
    data = {}

    team = Team.objects.get(pk=pk)
    data['form'] = TeamForm(request.POST or None, instance=team)

    if data['form'].is_valid():
        data['form'].save()
        return redirect('basket:teams_list')

    else:
        print("not saved")

    return render(request, template_name, data)


def player_delete(request, pk):
    player = Player.objects.get(pk=pk)
    player.delete()
    return redirect('basket:players_list')


def team_delete(request, pk):
    team = Team.objects.get(pk=pk)
    team.delete()
    return redirect('basket:teams_list')


def coach_delete(request, pk):
    coach = Coach.objects.get(pk=pk)
    coach.delete()
    return redirect('basket:coachs_list')

basket/templates/coach_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Coach</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

</head>
<body>
{% load bootstrap4 %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/basket/players/list">Players <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/basket/teams/list">Teams</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/basket/coachs/list">Coaches</a>
            </li>

        </ul>
    </div>
</nav>


<div class="container">
    <h1>Crear Coach</h1>
    <form method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        <input type="submit" name="" class="btn btn-primary" value="submit">

    </form>

</div>


<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

basket/templates/coach_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Coach</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/basket/players/list">Players <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/basket/teams/list">Teams</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/basket/coachs/list">Coaches</a>
            </li>

        </ul>
    </div>
</nav>


<div class="container">

    <a class="my-4" href="/basket/coachs/create">Crear Coach</a>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Equipo</th>
            <th scope="col">Acciones</th>
        </tr>
        </thead>
        <tbody>
        {% for coach in coachs %}
            <tr>
                <td>{{ coach.name }}</td>
                <td>{{ coach.team.name }}</td>
                <td>
                    <a class="btn-primary" href="{% url 'basket:coachs_update' coach.id %}">Editar</a>
                    <a class="btn-danger" href="{% url 'basket:coachs_delete' coach.id %}">Borrar</a>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
</div>


<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

basket/templates/coach_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Coach</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

</head>
<body>
{% load bootstrap4 %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/basket/players/list">Players <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/basket/teams/list">Teams</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/basket/coachs/list">Coaches</a>
            </li>

        </ul>
    </div>
</nav>


<div class="container">
    <h1>Crear Coach</h1>
    <form method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        <input type="submit" name="" class="btn btn-primary" value="submit">

    </form>

</div>


<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

basket/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Basket App</title>
</head>
<body>
    <h2>Last 5 players</h2>
        
    <ul>
        {% for player in last_5_players %}
        <li>{{player.name}} ({{player.nickname}})</li>
        {% endfor %}
    </ul>

    <h2>Last 5 Matchs</h2>
    <ul>
        {% for match in last_5_matchs %}
        <li>{{match.team1.player.first.team.name}} <strong>VS</strong> {{match.team2.player.first.team.name}}</li>
        {% endfor %}
    </ul>
    
    <h2>Teams</h2>
    <ul>
        {% for team in teams %}
        <li>{{team.name}} (tiene {{team.count_player}} jugadores)</li>
        {% endfor %}
    </ul>

</body>
</html>

basket/templates/matchs_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Coach</title>
</head>
<body>
    <body>
        <ul>
            {% for match in matchs %}
            <li>{{match.team1.player.first.team.name}} <strong>VS</strong> {{match.team2.player.first.team.name}}</li>
            {% endfor %}
        </ul>
    </body>
    </html>
</body>
</html>

basket/templates/players_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Coach</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

</head>
<body>
{% load bootstrap4 %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/basket/players/list">Players <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/basket/teams/list">Teams</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/basket/coachs/list">Coaches</a>
            </li>

        </ul>
    </div>
</nav>


<div class="container">
    <h1>Crear Player</h1>
    <form method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        <input type="submit" name="" class="btn btn-primary" value="submit">

    </form>

</div>


<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

basket/templates/players_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Player list</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/basket/players/list">Players <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/basket/teams/list">Teams</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/basket/coachs/list">Coaches</a>
            </li>

        </ul>
    </div>
</nav>

<div class="container">
    <a href="/basket/players/create">Crear Player</a>

    {% for team in teams %}
        <h2>{{ team.name }}</h2>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Apodo</th>
                <th scope="col">Posicion</th>
                <th scope="col">Acciones</th>
            </tr>
            </thead>
            <tbody>
            {% for player in team.players %}
                <tr>
                    <td>{{ player.name }}</td>
                    <td>{{ player.nickname }}</td>
                    <td>{{ player.position }}</td>
                    <td>
                        <a class="btn-primary" href="{% url 'basket:players_update' player.id %}">Editar</a>
                        <a class="btn-danger" href="{% url 'basket:players_delete' player.id %}">Borrar</a>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>



    {% endfor %}
</div>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

basket/templates/players_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Coach</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

</head>
<body>
{% load bootstrap4 %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/basket/players/list">Players <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/basket/teams/list">Teams</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/basket/coachs/list">Coaches</a>
            </li>

        </ul>
    </div>
</nav>


<div class="container">
    <h1>Editar player</h1>
    <form method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        <input type="submit" name="" class="btn btn-primary" value="submit">

    </form>

</div>


<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

basket/templates/team_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Team</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

</head>
<body>
{% load bootstrap4 %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/basket/players/list">Players <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/basket/teams/list">Teams</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/basket/coachs/list">Coaches</a>
            </li>

        </ul>
    </div>
</nav>


<div class="container">
    <h1>Crear Team</h1>
    <form method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        <input type="submit" name="" class="btn btn-primary" value="submit">

    </form>

</div>


<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

basket/templates/team_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Team</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

</head>
<body>
{% load bootstrap4 %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/basket/players/list">Players <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/basket/teams/list">Teams</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/basket/coachs/list">Coaches</a>
            </li>

        </ul>
    </div>
</nav>


<div class="container">
    <h1>Crear Team</h1>
    <form method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        <input type="submit" name="" class="btn btn-primary" value="submit">

    </form>

</div>


<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

basket/templates/teams_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Player list</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/basket/players/list">Players <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/basket/teams/list">Teams</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/basket/coachs/list">Coaches</a>
            </li>

        </ul>
    </div>
</nav>

<div class="container">
    <a class="my-4" href="/basket/team/create">Crear Team</a>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Coach</th>
            <th scope="col">Logo</th>
            <th scope="col">Acciones</th>
        </tr>
        </thead>
        <tbody>
        {% for team in teams %}
            <tr>
                <td>{{ team.name }}</td>
                <td>{{ team.coach.name }}</td>
                <td><img style="width: 50px" src="/media/{{ team.logo }}" alt=""></td>
                <td>
                    <a class="btn-primary" href="{% url 'basket:teams_update' team.id %}">Editar</a>
                    <a class="btn-danger" href="{% url 'basket:teams_delete' team.id %}">Borrar</a>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
</div>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>